config/urls.py
from django.contrib import admin
from django.urls import path, include
from firstapp import views
from . import views as config_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index1/', views.index1),
    path('index2/', views.index2),
    path('first/', include('firstapp.urls')),
    path('home/', config_views.home),
    path('second/', include('secondapp.urls')),
    path('third/', include('thirdapp.urls')),

    path('text/<str:char>/', config_views.text),
    path('<int:year>/<int:month>/', config_views.date),
    path('search/', config_views.search),
    path('info/', config_views.info),

    path('member/', include('member.urls')),
    path('paging/', include('paging.urls')),
    path('file/', include('file.urls')),
    
] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

file/urls.py
from django.urls import path
from . import views

app_name = 'file'

urlpatterns = [
    path('upload1/', views.upload1, name='upload1'),
    
]

paging/urls.py
from django.urls import path
from . import views

app_name = 'paging'

urlpatterns = [
    path('army_shop/', views.army_shop, name='army_shop'),
]

paging/models.py
from django.db import models

# Create your models here.

paging/views.py
from django.shortcuts import render
from secondapp.models import ArmyShop
from django.core.paginator import Paginator

def army_shop(request):
    now_page = request.GET.get('page', 1)
    #   LIMIT 시작번호, 개수

    datas = ArmyShop.objects.order_by('-id')

    p = Paginator(datas, 10)

    # 요청파라미터는 문자열
    now_page = int(now_page)
    
    info = p.page(now_page)

    start_page = (now_page - 1) // 10 * 10 + 1
    end_page = start_page + 9
    if end_page > p.num_pages:
        end_page = p.num_pages
    
    start_page = (now_page - 1) // 10 * 10 + 1
    end_page = start_page + 9
    if end_page > p.num_pages:
        end_page = p.num_pages
    
    context = {
        'info' : info,
        'page_range' : range(start_page, end_page + 1)
    }

    return render(request, 'paging/army_shop.html', context)

paging/templates/paging/army_shop.html
<link rel="stylesheet"
href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<body style='margin:30px;'>
    <table class='table table-striped'>
        <tr>
            <td>번호</td>
            <td>연도</td>
            <td>월</td>
            <td>제품명</td>
        </tr>

        {% for data in info %}
        <tr>
            <td>{{ data.id }}</td>
            <td>{{ data.year }}</td>
            <td>{{ data.month }}</td>
            <td>{{ data.name }}</td>
        </tr>
        {% endfor %}
    </table>

    <div style='text-align:center;'>
        <ul class='pagination'>
            {% for i in page_range %}
            <li>
            <a href='{% url "paging:army_shop" %}?page={{ i }}'>
                {{ i }}
            </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>