config/urls.py
from django.contrib import admin
from django.urls import path, include
from firstapp import views
from . import views as config_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index1/', views.index1),
    path('index2/', views.index2),
    path('first/', include('firstapp.urls')),
    path('home/', config_views.home),
    path('second/', include('secondapp.urls')),
    path('third/', include('thirdapp.urls')),

    path('text/<str:char>/', config_views.text),
    path('<int:year>/<int:month>/', config_views.date),
    path('search/', config_views.search),
    path('info/', config_views.info),

    path('member/', include('member.urls')),
    path('paging/', include('paging.urls')),
    path('file/', include('file.urls')),
    
] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

file/urls.py
from django.urls import path
from . import views

app_name = 'file'

urlpatterns = [
    path('upload1/', views.upload1, name='upload1'),
    
]

secondapp/urls.py
from django.urls import path
from . import views
app_name = 'secondapp'

urlpatterns = [
    path('main/', views.main),
    path('insert/', views.insert),
    path('show/', views.show, name = 'show'),
    path('army_shop/', views.army_shop),
    path('army_shop/<int:year>/<int:month>', views.army_shop2),
    path('req/ajax/get/', views.ajaxGet),
    path('req/ajax/exam/', views.ajaxExam),
    path('req/ajax/post/', views.ajaxPost),
    path('req/ajax/json/', views.ajaxJson),

    path('course/create/', views.course_create, name = 'course_create'),
]

secondapp/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=30)
    cnt = models.IntegerField()

    def __str__(self):
        return self.name

class ArmyShop(models.Model):
    year = models.IntegerField()
    month = models.IntegerField()
    type = models.TextField()
    name = models.TextField()

    class Meta:
        db_table = 'army_shop'
        ordering = ['-id','name']
        managed = False

secondapp/forms.py
from django import forms
from .models import Course

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course

        fields = ['name', 'cnt']  # id 속성은 PK 이므로 사용하지 않음

        labels = {  # 오류 메시지에 보여줄 단어
            'name': '과정명',
            'cnt': '인원수'
        }

secondapp/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse

from secondapp.forms import CourseForm
from .models import Course
from .models import ArmyShop

# Create your views here.
def main(request):
    return HttpResponse('<u>Main</u>')

def insert(request):
    Course.objects.create(name='데이터 분석', cnt=30)
    Course(name='데이터 수집', cnt=20).save()
    Course(name='웹개발', cnt=25).save()
    Course(name='인공지능', cnt=20).save()
    
    return HttpResponse('데이터 입력 완료')

def show(request):
    course = Course.objects.all()
    # result = ''
    # for c in course:
    #     # result += c.name + '<br>'
    #     result += '%s %s<br>' % (c.name, c.cnt)
    
    
    return render(
        request, 'secondapp/show.html',
        { 'data': course }
    )

def army_shop(request):
    # armyshop = ArmyShop.objects.all()
    # prd = request.GET.get('prd', '')        # 부작용 side effect
    
    prd = request.GET.get('prd', '')        # 부작용 side effect
    # prd = request.POST.get('prd', '')        # 부작용 side effect
    try:
        armyshop = ArmyShop.objects.filter(name__contains=prd)
    except:
        armyshop = ArmyShop.objects.all()
    
    return render(
        request, 'secondapp/army_shop.html',
        { 'data': armyshop }
    )

def army_shop2(request, year, month):
    armyshop = ArmyShop.objects.filter(year=year, month=month)
    
    # result = ''
    # for i in armyshop:
    #     result += '%s %s %s<br>' %(i.year, i.month, i.name)

    result = [ '%s %s %s<br>' %(i.year, i.month, i.name) for i in armyshop ]

    return HttpResponse(''.join(result))

from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.forms.models import model_to_dict
@csrf_exempt
def ajaxGet(request):

    # QuerySet []
    c = Course.objects.all()
    data = []

    # model_to_dict - 조회된 데이터를 dict 형태로 변경
    for a in c:
        d = model_to_dict(a)
        data.append(d)

    return JsonResponse( data, safe=False )

def ajaxExam(request):
    return render(request, 'secondapp/ajax_exam.html')

from django.views.decorators.csrf import csrf_exempt
@csrf_exempt
def ajaxPost(request):
    c = Course.objects.all()
    data = []

    # model_to_dict - 조회된 데이터를 dict 형태로 변경
    for a in c:
        d = model_to_dict(a)
        data.append(d)

    return JsonResponse( data, safe=False )

@csrf_exempt
def ajaxJson(request):
    c = Course.objects.all()
    data = []

    # model_to_dict - 조회된 데이터를 dict 형태로 변경
    for a in c:
        d = model_to_dict(a)
        data.append(d)

    return JsonResponse( data, safe=False )

def course_create(request):
    if request.method == 'POST':
        # form 미사용시 작성되는 코드
        # name = request.Post.get('name')
        # cnt = request.Post.get('cnt')
        # c = Course(name = name, cnt = cnt)
        # c.save()

        # 1. 입력된 데이터(요청 데이터)를 한꺼번에 저장
        # 2. 유효성 검사 결과 저장
        form = CourseForm(request.POST)
        if form.is_valid():
            # 데이터 저장
            course = form .save(commit = False)
            course.save()
            # 어딘가로 이동, 메시지 출력, ...
            
            return redirect('secondapp:show')

    else:
        form = CourseForm()

    return render(request, 'secondapp/course_create.html', 
        {'form' : form})

secondapp/templates/secondapp/ajax_exam.html
{% load static %}

<button id='get'>GET</button>
<button id='post'>POST</button>
<button id='json'>JSON</button>

<img src = '/static/zzanggu.jpg'>
<img src = '{% static "zzanggu.jpg" %}'>

<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
    // 이벤트 작성 (버튼 누르기)
    document.querySelector('#get').addEventListener('click', () => {
        const data = axios({
            url: '/second/req/ajax/get/',
            method: 'get',
            params: { }
        });
        data.then(function (result) {   // 비동기 작업 후 처리하는 CallBack
            console.log(result.data);
        });
    });

    document.querySelector('#post').addEventListener('click', () => {
        const data = axios({
            url: '/second/req/ajax/post/',
            method: 'post',
            params: { }
        });
        data.then(function (result) {   // 비동기 작업 후 처리하는 CallBack
            console.log(result.data);
        });
    });

    document.querySelector('#json').addEventListener('click', () => {
        const data = axios({
            url: '/second/req/ajax/json/',
            method: 'post',
            params: { }
        });
        data.then(function (result) {   // 비동기 작업 후 처리하는 CallBack
            console.log(result.data);
        });
    });
    
</script>

secondapp/templates/secondapp/army_shop.html
<body>
    <table border = "1">
        <th>순번</th>
        <th>연도</th>
        <th>월</th>
        <th>종류</th>
        <th>제품명</th>

        {% for item in data %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.year }}</td>
                <td>{{ item.month }}</td>
                <td>{{ item.type }}</td>
                <td>{{ item.name }}</td>
            </tr>
        {% endfor %}
    </table>
</body>

secondapp/templates/secondapp/course_create.html
<link rel="stylesheet"
  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<div class="container">
  <h5 class="my-3 border-bottom pb-2">과정 정보 입력</h5>

  <form method="post" action="{% url 'secondapp:course_create' %}" 
      class="post-form my-3">

    {% csrf_token %}

    {% comment %} 에러 부분을 include하면 좋음 {% endcomment %}
    {% if form.errors %}
      <div class="alert alert-danger" role="alert">
        {% for field in form %}
          {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
          {% endif %}
        {% endfor %}
      </div>
    {% endif %}

    <div class="form-group">
      <label for="name">과정명</label>
      <input type="text" class="form-control" name="name" id="name"
      value="{{ form.name.value | default_if_none:'' }}">
    </div>

    <div class="form-group">
      <label for="cnt">인원수</label>
      <input type="text" class="form-control" name="cnt" id="cnt"
      value="{{ form.cnt.value | default_if_none:'' }}">
    </div>

    <input type="submit" value="입력" class='btn btn-primary'>

  </form>

</div>

secondapp/templates/secondapp/show.html
<body>
    <h1>SecondApp</h1>
    <hr>
    {% for item in data %}
        <h3>{{ item.id }} / {{ item.name }} / {{ item.cnt }}</h3>
    {% endfor %}
</body>